sudo: required

language: cpp

services:
  - docker

before_install:
  - echo "$TRAVIS_TAG"
  - echo "$TRAVIS_BRANCH"

script:
  - if [ -n "${TRAVIS_TAG}" ]; then
    cd deploy/;
    ./deploy.sh;
    fi
  - docker images

notifications:
  slack: goloschain:sLr7BW0VhNtuv1xrMKJ8MSQb
