export const CONTAINER_MAX_WIDTH = 1150;
export const CONTAINER_MOBILE_WIDTH = 500;
export const CONTAINER_BASE_MARGIN = 20;
export const CONTAINER_FULL_WIDTH = CONTAINER_MAX_WIDTH + 2 * CONTAINER_BASE_MARGIN;
export const CONTAINER_MOBILE_MARGIN = 16;
export const SINGLE_COLUMN_WIDTH = 768;
