export const CREATE_POST = 'CREATE_POST';
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS';
export const CREATE_POST_ERROR = 'CREATE_POST_ERROR';

export const UPDATE_POST = 'UPDATE_POST';
export const UPDATE_POST_SUCCESS = 'UPDATE_POST_SUCCESS';
export const UPDATE_POST_ERROR = 'UPDATE_POST_ERROR';

export const DELETE_POST = 'DELETE_POST';
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';
export const DELETE_POST_ERROR = 'DELETE_POST_ERROR';

export const VOTE_POST = 'VOTE_POST';
export const VOTE_POST_SUCCESS = 'VOTE_POST_SUCCESS';
export const VOTE_POST_ERROR = 'VOTE_POST_ERROR';

export const FETCH_POST = 'FETCH_POST';
export const FETCH_POST_SUCCESS = 'FETCH_POST_SUCCESS';
export const FETCH_POST_ERROR = 'FETCH_POST_ERROR';

export const FETCH_PAGE_POST = 'FETCH_PAGE_POST';
export const FETCH_PAGE_POST_SUCCESS = 'FETCH_PAGE_POST_SUCCESS';
export const FETCH_PAGE_POST_ERROR = 'FETCH_PAGE_POST_ERROR';

export const FETCH_POSTS = 'FETCH_POSTS';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_ERROR = 'FETCH_POSTS_ERROR';

export const FETCH_POST_COMMENTS = 'FETCH_POST_COMMENTS';
export const FETCH_POST_COMMENTS_SUCCESS = 'FETCH_POST_COMMENTS_SUCCESS';
export const FETCH_POST_COMMENTS_ERROR = 'FETCH_POST_COMMENTS_ERROR';

export const FETCH_COMMENT = 'FETCH_COMMENT';
export const FETCH_COMMENT_SUCCESS = 'FETCH_COMMENT_SUCCESS';
export const FETCH_COMMENT_ERROR = 'FETCH_COMMENT_ERROR';

export const FETCH_FEED_COMMENTS = 'FETCH_FEED_COMMENTS';
export const FETCH_FEED_COMMENTS_SUCCESS = 'FETCH_FEED_COMMENTS_SUCCESS';
export const FETCH_FEED_COMMENTS_ERROR = 'FETCH_FEED_COMMENTS_ERROR';

export const UPDATE_UI_MODE = 'UPDATE_UI_MODE';

export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_ERROR = 'AUTH_LOGIN_ERROR';

export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_LOGOUT_SUCCESS = 'AUTH_LOGOUT_SUCCESS';

export const GATE_AUTHORIZE_SECRET = 'GATE_AUTHORIZE_SECRET';
export const GATE_AUTHORIZE_SECRET_SUCCESS = 'GATE_AUTHORIZE_SECRET_SUCCESS';
export const GATE_AUTHORIZE_SECRET_ERROR = 'GATE_AUTHORIZE_SECRET_ERROR';

export const GATE_AUTHORIZE = 'GATE_AUTHORIZE';
export const GATE_AUTHORIZE_SUCCESS = 'GATE_AUTHORIZE_SUCCESS';
export const GATE_AUTHORIZE_ERROR = 'GATE_AUTHORIZE_ERROR';

export const SET_SERVER_ACCOUNT_NAME = 'SET_SERVER_ACCOUNT_NAME';

export const SET_COMMENTS_FILTER = 'SET_COMMENTS_FILTER';

export const PROVIDE_BW = 'PROVIDE_BW';
export const PROVIDE_BW_SUCCESS = 'PROVIDE_BW_SUCCESS';
export const PROVIDE_BW_ERROR = 'PROVIDE_BW_ERROR';

export const UPDATE_PROFILE_DATA = 'UPDATE_PROFILE_DATA';
export const UPDATE_PROFILE_DATA_SUCCESS = 'UPDATE_PROFILE_DATA_SUCCESS';
export const UPDATE_PROFILE_DATA_ERROR = 'UPDATE_PROFILE_DATA_ERROR';

export const FETCH_CHARGERS = 'FETCH_CHARGERS';
export const FETCH_CHARGERS_SUCCESS = 'FETCH_CHARGERS_SUCCESS';
export const FETCH_CHARGERS_ERROR = 'FETCH_CHARGERS_ERROR';

export const FETCH_EMBED = 'FETCH_EMBED';
export const FETCH_EMBED_SUCCESS = 'FETCH_EMBED_SUCCESS';
export const FETCH_EMBED_ERROR = 'FETCH_EMBED_ERROR';

export const FETCH_HASHTAGTOP = 'FETCH_HASHTAGTOP';
export const FETCH_HASHTAGTOP_SUCCESS = 'FETCH_HASHTAGTOP_SUCCESS';
export const FETCH_HASHTAGTOP_ERROR = 'FETCH_HASHTAGTOP_ERROR';

/* for registration */
export const SET_SCREEN_ID = 'SET_SCREEN_ID';
export const SET_PHONE_NUMBER = 'SET_PHONE_NUMBER';
export const SET_LOCATION_DATA = 'SET_LOCATION_DATA';
export const SET_WISH_USERNAME = 'SET_WISH_USERNAME';
export const CLEAR_REGISTRATION_DATA = 'CLEAR_REGISTRATION_DATA';
export const SET_FULL_PHONE_NUMBER = 'SET_FULL_PHONE_NUMBER';
export const CLEAR_VERIFY_ERROR = 'CLEAR_VERIFY_ERROR';
export const CLEAR_REG_ERRORS = 'CLEAR_REG_ERRORS';
export const SET_LOCAL_STORAGE_DATA = 'SET_LOCAL_STORAGE_DATA';

export const FETCH_REG_FIRST_STEP = 'FETCH_REG_FIRST_STEP';
export const FETCH_REG_FIRST_STEP_SUCCESS = 'FETCH_REG_FIRST_STEP_SUCCESS';
export const FETCH_REG_FIRST_STEP_ERROR = 'FETCH_REG_FIRST_STEP_ERROR';
export const SET_FIRST_STEP_ERROR = 'SET_FIRST_STEP_ERROR';
export const FIRST_STEP_STOP_LOADER = 'FIRST_STEP_STOP_LOADER';

export const FETCH_REG_VERIFY = 'FETCH_REG_VERIFY';
export const FETCH_REG_VERIFY_SUCCESS = 'FETCH_REG_VERIFY_SUCCESS';
export const FETCH_REG_VERIFY_ERROR = 'FETCH_REG_VERIFY_ERROR';

export const FETCH_REG_SET_USER = 'FETCH_REG_SET_USER';
export const FETCH_REG_SET_USER_SUCCESS = 'FETCH_REG_SET_USER_SUCCESS';
export const FETCH_REG_SET_USER_ERROR = 'FETCH_REG_SET_USER_ERROR';

export const START_REG_BLOCK_CHAIN = 'START_REG_BLOCK_CHAIN';
export const FETCH_REG_BLOCK_CHAIN = 'FETCH_REG_BLOCK_CHAIN';
export const FETCH_REG_BLOCK_CHAIN_SUCCESS = 'FETCH_REG_BLOCK_CHAIN_SUCCESS';
export const FETCH_REG_BLOCK_CHAIN_ERROR = 'FETCH_REG_BLOCK_CHAIN_ERROR';
export const BLOCK_CHAIN_STOP_LOADER = 'BLOCK_CHAIN_STOP_LOADER';
export const SET_USERS_KEYS = 'SET_USERS_KEYS';

export const FETCH_RESEND_SMS = 'FETCH_RESEND_SMS';
export const FETCH_RESEND_SMS_SUCCESS = 'FETCH_RESEND_SMS_SUCCESS';
export const FETCH_RESEND_SMS_ERROR = 'FETCH_RESEND_SMS_ERROR';

export const SET_POST_VOTE = 'SET_POST_VOTE';
export const SET_COMMENT_VOTE = 'SET_COMMENT_VOTE';

export const FOLLOW_USER = 'FOLLOW_USER';
export const FOLLOW_USER_SUCCESS = 'FOLLOW_USER_SUCCESS';
export const FOLLOW_USER_ERROR = 'FOLLOW_USER_ERROR';

export const UNFOLLOW_USER = 'UNFOLLOW_USER';
export const UNFOLLOW_USER_SUCCESS = 'UNFOLLOW_USER_SUCCESS';
export const UNFOLLOW_USER_ERROR = 'UNFOLLOW_USER_ERROR';

export const BLOCK_USER = 'BLOCK_USER';
export const BLOCK_USER_SUCCESS = 'BLOCK_USER_SUCCESS';
export const BLOCK_USER_ERROR = 'BLOCK_USER_ERROR';

export const UNBLOCK_USER = 'UNBLOCK_USER';
export const UNBLOCK_USER_SUCCESS = 'UNBLOCK_USER_SUCCESS';
export const UNBLOCK_USER_ERROR = 'UNBLOCK_USER_ERROR';

export const VOTE_WITNESS = 'VOTE_WITNESS';
export const VOTE_WITNESS_SUCCESS = 'VOTE_WITNESS_SUCCESS';
export const VOTE_WITNESS_ERROR = 'VOTE_WITNESS_ERROR';

export const UNVOTE_WITNESS = 'UNVOTE_WITNESS';
export const UNVOTE_WITNESS_SUCCESS = 'UNVOTE_WITNESS_SUCCESS';
export const UNVOTE_WITNESS_ERROR = 'UNVOTE_WITNESS_ERROR';

export const TRANSFER_TOKEN = 'TRANSFER_TOKEN';
export const TRANSFER_TOKEN_SUCCESS = 'TRANSFER_TOKEN_SUCCESS';
export const TRANSFER_TOKEN_ERROR = 'TRANSFER_TOKEN_ERROR';

export const UPDATE_AUTH = 'UPDATE_AUTH';
export const UPDATE_AUTH_SUCCESS = 'UPDATE_AUTH_SUCCESS';
export const UPDATE_AUTH_ERROR = 'UPDATE_AUTH_ERROR';

export const WITHDRAW = 'WITHDRAW';
export const WITHDRAW_SUCCESS = 'WITHDRAW_SUCCESS';
export const WITHDRAW_ERROR = 'WITHDRAW_ERROR';

export const STOP_WITHDRAW = 'STOP_WITHDRAW';
export const STOP_WITHDRAW_SUCCESS = 'STOP_WITHDRAW_SUCCESS';
export const STOP_WITHDRAW_ERROR = 'STOP_WITHDRAW_ERROR';

export const DELEGATE = 'DELEGATE';
export const DELEGATE_SUCCESS = 'DELEGATE_SUCCESS';
export const DELEGATE_ERROR = 'DELEGATE_ERROR';

export const FETCH_NOTIFICATIONS = 'FETCH_NOTIFICATIONS';
export const FETCH_NOTIFICATIONS_SUCCESS = 'FETCH_NOTIFICATIONS_SUCCESS';
export const FETCH_NOTIFICATIONS_ERROR = 'FETCH_NOTIFICATIONS_ERROR';

export const FETCH_ACTIVITY = 'FETCH_ACTIVITY';
export const FETCH_ACTIVITY_SUCCESS = 'FETCH_ACTIVITY_SUCCESS';
export const FETCH_ACTIVITY_ERROR = 'FETCH_ACTIVITY_ERROR';

export const MARK_ALL_NOTIFICATIONS_VIEWED = 'MARK_ALL_NOTIFICATIONS_VIEWED';
export const MARK_ALL_NOTIFICATIONS_VIEWED_SUCCESS = 'MARK_ALL_NOTIFICATIONS_VIEWED_SUCCESS';
export const MARK_ALL_NOTIFICATIONS_VIEWED_ERROR = 'MARK_ALL_NOTIFICATIONS_VIEWED_ERROR';

export const MARK_NOTIFICATION_VIEWED = 'MARK_NOTIFICATION_VIEWED';
export const MARK_NOTIFICATION_VIEWED_SUCCESS = 'MARK_NOTIFICATION_VIEWED_SUCCESS';
export const MARK_NOTIFICATION_VIEWED_ERROR = 'MARK_NOTIFICATION_VIEWED_ERROR';

export const FETCH_SETTINGS = 'FETCH_SETTINGS';
export const FETCH_SETTINGS_SUCCESS = 'FETCH_SETTINGS_SUCCESS';
export const FETCH_SETTINGS_ERROR = 'FETCH_SETTINGS_ERROR';

export const UPDATE_SETTINGS = 'UPDATE_SETTINGS';
export const UPDATE_SETTINGS_SUCCESS = 'UPDATE_SETTINGS_SUCCESS';
export const UPDATE_SETTINGS_ERROR = 'UPDATE_SETTINGS_ERROR';

export const RECORD_POST_VIEW = 'RECORD_POST_VIEW';
export const RECORD_POST_VIEW_SUCCESS = 'RECORD_POST_VIEW_SUCCESS';
export const RECORD_POST_VIEW_ERROR = 'RECORD_POST_VIEW_ERROR';

export const FETCH_FAVORITES = 'FETCH_FAVORITES';
export const FETCH_FAVORITES_SUCCESS = 'FETCH_FAVORITES_SUCCESS';
export const FETCH_FAVORITES_ERROR = 'FETCH_FAVORITES_ERROR';

export const ADD_FAVORITE = 'ADD_FAVORITE';
export const ADD_FAVORITE_SUCCESS = 'ADD_FAVORITE_SUCCESS';
export const ADD_FAVORITE_ERROR = 'ADD_FAVORITE_ERROR';

export const REMOVE_FAVORITE = 'REMOVE_FAVORITE';
export const REMOVE_FAVORITE_SUCCESS = 'REMOVE_FAVORITE_SUCCESS';
export const REMOVE_FAVORITE_ERROR = 'REMOVE_FAVORITE_ERROR';

export const FETCH_USER_REPLIES = 'FETCH_USER_REPLIES';
export const FETCH_USER_REPLIES_SUCCESS = 'FETCH_USER_REPLIES_SUCCESS';
export const FETCH_USER_REPLIES_ERROR = 'FETCH_USER_REPLIES_ERROR';

export const FETCH_USER_BALANCE = 'FETCH_USER_BALANCE';
export const FETCH_USER_BALANCE_SUCCESS = 'FETCH_USER_BALANCE_SUCCESS';
export const FETCH_USER_BALANCE_ERROR = 'FETCH_USER_BALANCE_ERROR';

export const FETCH_TRANSFERS_HISTORY = 'FETCH_TRANSFERS_HISTORY';
export const FETCH_TRANSFERS_HISTORY_SUCCESS = 'FETCH_TRANSFERS_HISTORY_SUCCESS';
export const FETCH_TRANSFERS_HISTORY_ERROR = 'FETCH_TRANSFERS_HISTORY_ERROR';

export const FETCH_REWARDS_HISTORY = 'FETCH_REWARDS_HISTORY';
export const FETCH_REWARDS_HISTORY_SUCCESS = 'FETCH_REWARDS_HISTORY_SUCCESS';
export const FETCH_REWARDS_HISTORY_ERROR = 'FETCH_REWARDS_HISTORY_ERROR';

export const FETCH_VESTING_HISTORY = 'FETCH_VESTING_HISTORY';
export const FETCH_VESTING_HISTORY_SUCCESS = 'FETCH_VESTING_HISTORY_SUCCESS';
export const FETCH_VESTING_HISTORY_ERROR = 'FETCH_VESTING_HISTORY_ERROR';

export const FETCH_GENESIS_CONVERSIONS = 'FETCH_GENESIS_CONVERSIONS';
export const FETCH_GENESIS_CONVERSIONS_SUCCESS = 'FETCH_GENESIS_CONVERSIONS_SUCCESS';
export const FETCH_GENESIS_CONVERSIONS_ERROR = 'FETCH_GENESIS_CONVERSIONS_ERROR';

export const FETCH_VESTING_PARAMS = 'FETCH_VESTING_PARAMS';
export const FETCH_VESTING_PARAMS_SUCCESS = 'FETCH_VESTING_PARAMS_SUCCESS';
export const FETCH_VESTING_PARAMS_ERROR = 'FETCH_VESTING_PARAMS_ERROR';

export const FETCH_ACCOUNT = 'FETCH_ACCOUNT';
export const FETCH_ACCOUNT_SUCCESS = 'FETCH_ACCOUNT_SUCCESS';
export const FETCH_ACCOUNT_ERROR = 'FETCH_ACCOUNT_ERROR';

export const REBLOG_POST = 'REBLOG_POST';
export const REBLOG_POST_SUCCESS = 'REBLOG_POST_SUCCESS';
export const REBLOG_POST_ERROR = 'REBLOG_POST_ERROR';

export const FETCH_NOTIFICATIONS_COUNT = 'FETCH_NOTIFICATIONS_COUNT';
export const FETCH_NOTIFICATIONS_COUNT_SUCCESS = 'FETCH_NOTIFICATIONS_COUNT_SUCCESS';
export const FETCH_NOTIFICATIONS_COUNT_ERROR = 'FETCH_NOTIFICATIONS_COUNT_ERROR';

export const FETCH_LEADERS = 'FETCH_LEADERS';
export const FETCH_LEADERS_SUCCESS = 'FETCH_LEADERS_SUCCESS';
export const FETCH_LEADERS_ERROR = 'FETCH_LEADERS_ERROR';

export const FETCH_ACTUAL_RATES = 'FETCH_ACTUAL_RATES';
export const FETCH_ACTUAL_RATES_SUCCESS = 'FETCH_ACTUAL_RATES_SUCCESS';
export const FETCH_ACTUAL_RATES_ERROR = 'FETCH_ACTUAL_RATES_ERROR';

export const FETCH_POST_VOTES = 'FETCH_POST_VOTES';
export const FETCH_POST_VOTES_SUCCESS = 'FETCH_POST_VOTES_SUCCESS';
export const FETCH_POST_VOTES_ERROR = 'FETCH_POST_VOTES_ERROR';

export const FETCH_COMMENT_VOTES = 'FETCH_COMMENT_VOTES';
export const FETCH_COMMENT_VOTES_SUCCESS = 'FETCH_COMMENT_VOTES_SUCCESS';
export const FETCH_COMMENT_VOTES_ERROR = 'FETCH_COMMENT_VOTES_ERROR';

export const FETCH_FOLLOWING = 'FETCH_FOLLOWING';
export const FETCH_FOLLOWING_SUCCESS = 'FETCH_FOLLOWING_SUCCESS';
export const FETCH_FOLLOWING_ERROR = 'FETCH_FOLLOWING_ERROR';

export const FETCH_FOLLOWERS = 'FETCH_FOLLOWERS';
export const FETCH_FOLLOWERS_SUCCESS = 'FETCH_FOLLOWERS_SUCCESS';
export const FETCH_FOLLOWERS_ERROR = 'FETCH_FOLLOWERS_ERROR';

export const REG_WITNESS = 'REG_WITNESS';
export const REG_WITNESS_SUCCESS = 'REG_WITNESS_SUCCESS';
export const REG_WITNESS_ERROR = 'REG_WITNESS_ERROR';

export const FETCH_PROPOSALS = 'FETCH_PROPOSALS';
export const FETCH_PROPOSALS_SUCCESS = 'FETCH_PROPOSALS_SUCCESS';
export const FETCH_PROPOSALS_ERROR = 'FETCH_PROPOSALS_ERROR';

export const FETCH_PROPOSAL = 'FETCH_PROPOSAL';
export const FETCH_PROPOSAL_SUCCESS = 'FETCH_PROPOSAL_SUCCESS';
export const FETCH_PROPOSAL_ERROR = 'FETCH_PROPOSAL_ERROR';

export const STOP_WITNESS = 'STOP_WITNESS';
export const STOP_WITNESS_SUCCESS = 'STOP_WITNESS_SUCCESS';
export const STOP_WITNESS_ERROR = 'STOP_WITNESS_ERROR';

export const REMOVE_REBLOG_POST = 'REMOVE_REBLOG_POST';
export const REMOVE_REBLOG_POST_SUCCESS = 'REMOVE_REBLOG_POST_SUCCESS';
export const REMOVE_REBLOG_POST_ERROR = 'REMOVE_REBLOG_POST_ERROR';

export const CONVERT_VESTING_TO_TOKEN = 'CONVERT_VESTING_TO_TOKEN';
export const CONVERT_VESTING_TO_TOKEN_SUCCESS = 'CONVERT_VESTING_TO_TOKEN_SUCCESS';
export const CONVERT_VESTING_TO_TOKEN_ERROR = 'CONVERT_VESTING_TO_TOKEN_ERROR';

export const CONVERT_TOKENS_TO_VESTING = 'CONVERT_TOKENS_TO_VESTING';
export const CONVERT_TOKENS_TO_VESTING_SUCCESS = 'CONVERT_TOKENS_TO_VESTING_SUCCESS';
export const CONVERT_TOKENS_TO_VESTING_ERROR = 'CONVERT_TOKENS_TO_VESTING_ERROR';

export const FETCH_VESTING_SUPPLY_AND_BALANCE = 'FETCH_VESTING_SUPPLY_AND_BALANCE';
export const FETCH_VESTING_SUPPLY_AND_BALANCE_SUCCESS = 'FETCH_VESTING_SUPPLY_AND_BALANCE_SUCCESS';
export const FETCH_VESTING_SUPPLY_AND_BALANCE_ERROR = 'FETCH_VESTING_SUPPLY_AND_BALANCE_ERROR';

export const FETCH_NOTIFY_META = 'FETCH_NOTIFY_META';
export const FETCH_NOTIFY_META_SUCCESS = 'FETCH_NOTIFY_META_SUCCESS';
export const FETCH_NOTIFY_META_ERROR = 'FETCH_NOTIFY_META_ERROR';

export const APPROVE_PROPOSAL = 'APPROVE_PROPOSAL';
export const APPROVE_PROPOSAL_SUCCESS = 'APPROVE_PROPOSAL_SUCCESS';
export const APPROVE_PROPOSAL_ERROR = 'APPROVE_PROPOSAL_ERROR';

export const EXEC_PROPOSAL = 'EXEC_PROPOSAL';
export const EXEC_PROPOSAL_SUCCESS = 'EXEC_PROPOSAL_SUCCESS';
export const EXEC_PROPOSAL_ERROR = 'EXEC_PROPOSAL_ERROR';

export const CLAIM_TOKEN = 'CLAIM_TOKEN';
export const CLAIM_TOKEN_SUCCESS = 'CLAIM_TOKEN_SUCCESS';
export const CLAIM_TOKEN_ERROR = 'CLAIM_TOKEN_ERROR';

export const WITHDRAW_STAKE = 'WITHDRAW_STAKE';
export const WITHDRAW_STAKE_SUCCESS = 'WITHDRAW_STAKE_SUCCESS';
export const WITHDRAW_STAKE_ERROR = 'WITHDRAW_STAKE_ERROR';

export const FETCH_CLAIM_HISTORY = 'FETCH_CLAIM_HISTORY';
export const FETCH_CLAIM_HISTORY_SUCCESS = 'FETCH_CLAIM_HISTORY_SUCCESS';
export const FETCH_CLAIM_HISTORY_ERROR = 'FETCH_CLAIM_HISTORY_ERROR';

export const FETCH_VALIDATORS = 'FETCH_VALIDATORS';
export const FETCH_VALIDATORS_SUCCESS = 'FETCH_VALIDATORS_SUCCESS';
export const FETCH_VALIDATORS_ERROR = 'FETCH_VALIDATORS_ERROR';

export const FETCH_DELEGATION_STATE = 'FETCH_DELEGATION_STATE';
export const FETCH_DELEGATION_STATE_SUCCESS = 'FETCH_DELEGATION_STATE_SUCCESS';
export const FETCH_DELEGATION_STATE_ERROR = 'FETCH_DELEGATION_STATE_ERROR';

export const FETCH_VESTING_PROPOSALS = 'FETCH_VESTING_PROPOSALS';
export const FETCH_VESTING_PROPOSALS_SUCCESS = 'FETCH_VESTING_PROPOSALS_SUCCESS';
export const FETCH_VESTING_PROPOSALS_ERROR = 'FETCH_VESTING_PROPOSALS_ERROR';

export const ACCEPT_VESTING_PROPOSAL = 'ACCEPT_VESTING_PROPOSAL';
export const ACCEPT_VESTING_PROPOSAL_SUCCESS = 'ACCEPT_VESTING_PROPOSAL_SUCCESS';
export const ACCEPT_VESTING_PROPOSAL_ERROR = 'FETCH_PROPOSALS_ERROR';
