export const MODAL_CONFIRM = 'MODAL_CONFIRM';
export const MODAL_CANCEL = 'MODAL_CANCEL';

export const SHOW_MODAL_CONFIRM = 'SHOW_MODAL_CONFIRM';
export const SHOW_MODAL_LOGIN = 'SHOW_MODAL_LOGIN';
export const SHOW_MODAL_LOGIN_OLD = 'SHOW_MODAL_LOGIN_OLD';
export const SHOW_MODAL_SIGNUP = 'SHOW_MODAL_SIGNUP';
export const SHOW_MODAL_BECOME_LOADER = 'SHOW_MODAL_BECOME_LOADER';
export const SHOW_MODAL_MANAGE_COMMUNITY = 'SHOW_MODAL_MANAGE_COMMUNITY';
export const SHOW_MODAL_REPOST = 'SHOW_MODAL_REPOST';
export const SHOW_MODAL_TRANSFER = 'SHOW_MODAL_TRANSFER';
export const SHOW_MODAL_DELEGATE = 'SHOW_MODAL_DELEGATE';
export const SHOW_MODAL_CONVERT = 'SHOW_MODAL_CONVERT';
export const SHOW_MODAL_VOTERS = 'SHOW_MODAL_VOTERS';
export const SHOW_MODAL_QR_KEY = 'SHOW_MODAL_QR_KEY';
export const SHOW_MODAL_PAYOUT_INFO = 'SHOW_MODAL_PAYOUT_INFO';
export const SHOW_MODAL_DISLIKE_ALERT = 'SHOW_MODAL_DISLIKE_ALERT';
export const SHOW_MODAL_UNFOLLOW_ALERT = 'SHOW_MODAL_UNFOLLOW_ALERT';
export const SHOW_MODAL_FOLLOWERS = 'SHOW_MODAL_FOLLOWERS';
export const SHOW_MODAL_LINK_OPTIONS = 'SHOW_MODAL_LINK_OPTIONS';
export const SHOW_MODAL_DELEGATE_VOTE = 'SHOW_MODAL_DELEGATE_VOTE';
export const SHOW_MODAL_ADD_IMAGE = 'SHOW_MODAL_ADD_IMAGE';
export const SHOW_MODAL_CUSTOM_PROPOSAL = 'SHOW_MODAL_CUSTOM_PROPOSAL';

export const OPENED_FROM_LOGIN = 'OPENED_FROM_LOGIN';
