export const MODAL_CONFIRM = 'MODAL_CONFIRM';
export const MODAL_CANCEL = 'MODAL_CANCEL';

export const SHOW_MODAL_CONFIRM = 'SHOW_MODAL_CONFIRM';
export const SHOW_MODAL_LOGIN = 'SHOW_MODAL_LOGIN';
export const SHOW_MODAL_SIGNUP = 'SHOW_MODAL_SIGNUP';

export const OPENED_FROM_LOGIN = 'OPENED_FROM_LOGIN';
