export const PHONE_SCREEN_ID = 'PNONE_SCREEN_ID';
export const CONFIRM_CODE_SCREEN_ID = 'CONFIRM_CODE_SCREEN_ID';
export const CREATE_USERNAME_SCREEN_ID = 'CREATE_USERNAME_SCREEN_ID';
export const MASTER_KEY_SCREEN_ID = 'MASTER_KEY_SCREEN_ID';
export const CONGRATULATIONS_SCREEN_ID = 'CONGRATULATIONS_SCREEN_ID';

export const MILLISECONDS_IN_SECOND = 1000;
