import {
  FETCH_USER_BALANCE,
  FETCH_USER_BALANCE_SUCCESS,
  FETCH_USER_BALANCE_ERROR,
  FETCH_TRANSFERS_HISTORY,
  FETCH_TRANSFERS_HISTORY_SUCCESS,
  FETCH_TRANSFERS_HISTORY_ERROR,
  FETCH_VESTING_HISTORY,
  FETCH_VESTING_HISTORY_SUCCESS,
  FETCH_VESTING_HISTORY_ERROR,
  FETCH_CLAIM_HISTORY,
  FETCH_CLAIM_HISTORY_SUCCESS,
  FETCH_CLAIM_HISTORY_ERROR,
  FETCH_REWARDS_HISTORY,
  FETCH_REWARDS_HISTORY_SUCCESS,
  FETCH_REWARDS_HISTORY_ERROR,
  FETCH_GENESIS_CONVERSIONS,
  FETCH_GENESIS_CONVERSIONS_SUCCESS,
  FETCH_GENESIS_CONVERSIONS_ERROR,
} from 'store/constants';

const initialState = {
  isLoading: false,
};

export default function(state = initialState, { type }) {
  switch (type) {
    case FETCH_USER_BALANCE:
    case FETCH_TRANSFERS_HISTORY:
    case FETCH_VESTING_HISTORY:
    case FETCH_CLAIM_HISTORY:
    case FETCH_REWARDS_HISTORY:
    case FETCH_GENESIS_CONVERSIONS:
      return {
        isLoading: true,
      };

    case FETCH_USER_BALANCE_SUCCESS:
    case FETCH_USER_BALANCE_ERROR:
    case FETCH_TRANSFERS_HISTORY_SUCCESS:
    case FETCH_TRANSFERS_HISTORY_ERROR:
    case FETCH_VESTING_HISTORY_SUCCESS:
    case FETCH_VESTING_HISTORY_ERROR:
    case FETCH_CLAIM_HISTORY_SUCCESS:
    case FETCH_CLAIM_HISTORY_ERROR:
    case FETCH_REWARDS_HISTORY_SUCCESS:
    case FETCH_REWARDS_HISTORY_ERROR:
    case FETCH_GENESIS_CONVERSIONS_SUCCESS:
    case FETCH_GENESIS_CONVERSIONS_ERROR:
      return {
        isLoading: false,
      };

    default:
      return state;
  }
}
